apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-volume
  template:
    metadata:
      labels:
        app: teste-volume
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: pv-container
          image: nginx
          ports:
            - containerPort: 80
              name: "http"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: pv-storage